apiVersion: v1
kind: Pod
metadata:
  name: database-migration
  namespace: toeic-app
  labels:
    job: database-migration
spec:
  restartPolicy: Never
  initContainers:
  - name: wait-for-postgres
    image: postgres:14-alpine
    command:
    - sh
    - -c
    - |
      until pg_isready -h postgres-service -p 5432 -U $DB_USER; do
        echo "Waiting for PostgreSQL..."
        sleep 2
      done
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: toeic-backend-secrets
          key: DB_USER
  containers:
  - name: migrate
    image: toeic-backend:latest
    command:
    - sh
    - -c
    - |
      echo "Running database migrations..."
      # Add your migration commands here
      # Example: ./migrate up
      echo "Migrations completed"
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: toeic-backend-config
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: toeic-backend-config
          key: DB_PORT
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: toeic-backend-config
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: toeic-backend-secrets
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: toeic-backend-secrets
          key: DB_PASSWORD
