apiVersion: v1
kind: ServiceAccount
metadata:
  name: toeic-backend-sa
  namespace: toeic-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: toeic-app
  name: toeic-backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toeic-backend-rolebinding
  namespace: toeic-app
subjects:
- kind: ServiceAccount
  name: toeic-backend-sa
  namespace: toeic-app
roleRef:
  kind: Role
  name: toeic-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server-sa
  namespace: toeic-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-server-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/stats", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server-rolebinding
subjects:
- kind: ServiceAccount
  name: metrics-server-sa
  namespace: toeic-app
roleRef:
  kind: ClusterRole
  name: metrics-server-role
  apiGroup: rbac.authorization.k8s.io
