analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.chopper.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
    - "**/*.swagger.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbserver.dart"
    - "lib/i18n/translations.dart"
    - "lib/i18n/translations*.dart"
    - "lib/generated/**"
    - "**/generated/**"
    - "**/gen/**"
    - "build/**"
  errors:
    duplicate_ignore: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: ignore
    unnecessary_non_null_assertion: ignore
  language:
    strict-casts: true
  plugins: 
    - custom_lint
    
include: package:flutter_lints/flutter.yaml
formatter:
  trailing_commas: preserve
dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  metrics:
    cyclomatic-complexity: 10
    number-of-parameters: 4
    maximum-nesting-level: 3
    source-lines-of-code: 50
    number-of-methods: 10

  anti-patterns:
    - long-method
    - long-parameter-list
    - god-class
    - excessive-nesting
  
  rules:
    - no-equal-then-else
    - no-boolean-literal-compare
    - no-magic-number
    - prefer-match-file-name
    - avoid-duplicate-exports
    - prefer-early-return

    - avoid-nested-conditional-expressions
    - avoid-unnecessary-type-assertions
    - avoid-missing-enum-constant-in-map
    - newline-before-return

   
    - avoid-global-state
    - avoid-long-files
    - avoid-returning-widgets
    - prefer-moving-to-variable
    - avoid-throw-in-catch-block
    - avoid-dynamic
    - avoid-nested-switches
    - avoid-preserve-whitespace
    - no-object-declaration
    - prefer-extracting-callbacks

    
    - avoid-unnecessary-type-casts
    - double-literal-format
    - avoid-ignoring-return-values
    
linter:
  rules:
    - always_put_control_body_on_new_line
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - diagnostic_describe_all_properties
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - flutter_style_todos
    - join_return_with_assignment
    - library_private_types_in_public_api
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - null_closures
    - package_names
    - parameter_assignments
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_setters_to_change_properties
    - valid_regexps
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_private_typedef_functions
    - avoid_returning_null_for_void
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - directives_ordering
    - implicit_call_tearoffs
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - noop_primitive_operations
    - prefer_asserts_with_message
    - prefer_expression_function_bodies
    - prefer_final_parameters
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - sized_box_shrink_expand
    - throw_in_finally
    - unnecessary_await_in_return
    - unnecessary_constructor_name
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_to_list_in_spreads
    - use_decorated_box
    - use_named_constants
    - use_string_buffers
    - use_test_throws_matchers
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - file_names    
    - lines_longer_than_80_chars
    - only_throw_errors
    - package_api_docs
    - prefer_conditional_assignment
    - prefer_final_locals
    - provide_deprecation_message
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_getters_setters
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - use_rethrow_when_possible
    - use_super_parameters
    - avoid_dynamic_calls
    - avoid_catching_errors
    - comment_references
    - eol_at_end_of_file
    - library_annotations
    - library_prefixes
    - matching_super_parameters
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - slash_for_doc_comments    
    - unnecessary_library_directive
    - unreachable_from_main
    - use_if_null_to_convert_nulls_to_bools
    - use_raw_strings
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_overrides
    - use_enums
    - avoid_renaming_method_parameters
    - avoid_returning_this
    - avoid_single_cascade_in_expression_statements
    - use_colored_box
    - prefer_const_constructors_in_immutables
