analyzer:
  errors:
    duplicate_ignore: ignore
    invalid_annotation_target: ignore
    unused_element_parameter: ignore
    unnecessary_non_null_assertion: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_control_body_on_new_line
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - diagnostic_describe_all_properties
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - flutter_style_todos
    - join_return_with_assignment
    - library_private_types_in_public_api
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - null_closures
    - package_names
    - parameter_assignments
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_setters_to_change_properties
    - valid_regexps
