name: learn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  get_it: ^8.0.3
  slang: ^4.7.1
  dart_either: ^2.0.0
  injectable: ^2.5.0
  logger: ^2.5.0
  slang_flutter: ^4.7.0
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  flutter_hooks: ^0.21.2
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  hooks_riverpod: ^2.6.1  
  material_symbols_icons: ^4.2815.1
  shimmer_animation: ^2.2.2
  dynamic_color: ^1.7.0
  package_info_plus: ^8.3.0
  flutter_html: ^3.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  slang_build_runner: ^4.7.0
  injectable_generator: ^2.7.0
  go_router_builder: ^2.9.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true