// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9WGbJCjNVymFPo9ZSHAbYLiNSsruyXe4',
    appId: '1:876124647158:web:c6afe62adce9277655c6d7',
    messagingSenderId: '876124647158',
    projectId: 'toeic-project-ict',
    authDomain: 'toeic-project-ict.firebaseapp.com',
    storageBucket: 'toeic-project-ict.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm9cr7SI-RiIv4AoLbfO8GaIF8Gz9TOVk',
    appId: '1:876124647158:android:5025f63daffb043655c6d7',
    messagingSenderId: '876124647158',
    projectId: 'toeic-project-ict',
    storageBucket: 'toeic-project-ict.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHzz6fabJiVA2rcJK1eHHe1OLtIG_iM_Y',
    appId: '1:876124647158:ios:e0a8201d856395f855c6d7',
    messagingSenderId: '876124647158',
    projectId: 'toeic-project-ict',
    storageBucket: 'toeic-project-ict.firebasestorage.app',
    iosBundleId: 'com.haruma.toeic.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHzz6fabJiVA2rcJK1eHHe1OLtIG_iM_Y',
    appId: '1:876124647158:ios:e0a8201d856395f855c6d7',
    messagingSenderId: '876124647158',
    projectId: 'toeic-project-ict',
    storageBucket: 'toeic-project-ict.firebasestorage.app',
    iosBundleId: 'com.haruma.toeic.learn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9WGbJCjNVymFPo9ZSHAbYLiNSsruyXe4',
    appId: '1:876124647158:web:a818c399df85b4b755c6d7',
    messagingSenderId: '876124647158',
    projectId: 'toeic-project-ict',
    authDomain: 'toeic-project-ict.firebaseapp.com',
    storageBucket: 'toeic-project-ict.firebasestorage.app',
  );
}
